### PR TITLE
Conversion to metanorma asciidoc

### PR DESCRIPTION
**Pull request by ghobona**

### CODE REVIEW

**Comment by ghobona** [comment]
@TaehoonK This Pull Request is not ready for merging. I will let you know when it is ready.

**Comment by ghobona** [comment]
@TaehoonK I'm ready to merge the metanorma branch into the master branch.

A daily build of the metanorma-compiled document is at https://opengeospatial.github.io/ogcna-auto-review/22-003.html

Please let me know by 12:00 UTC on Monday 11 December if any edits are required on this Pull Request. I will merge the Pull Request shortly after.

**Comment by TaehoonK** [comment]
@ghobona Thank you for converting to the metanorma version. 
But all JSON files and YAML schemas look like one-line flattened text (like *.min.js), such as Figure 2, 4, 5, 8, 9, and so on. 
How could we fix it?

**Comment by ghobona** [comment]
@TaehoonK Thanks for spotting the issue. The bug appears to have been introduced by the latest version of metanorma. I have just raised a ticket ( https://github.com/metanorma/metanorma-ogc/issues/614 ) with the maintainers of metanorma.

I have also changed the version of metanorma that is imported by the GitHub Action to a previous version that does not have the issue. So the next time the document compiles, the issue will hopefully not be there.

**Comment by TaehoonK** [comment]
@ghobona Thank you for your quick action. 
I confirmed that it builds on an older version (1.6.4), not a newer version, without the issues mentioned before. 
The color style hasn't been applied yet, but hopefully, that will be fixed soon. 

However, I did find a few issues: 
1. there is no Example 17; perhaps "Example - leaf parameter valid (and invalid) examples" should be 17. 
2. the style of the figure captions is not uniform (font size and background, etc.) For example, Figure 2 and Figure 3 are presented in a different style. could this be fixed? 
3. I think the size of the figures needs to be adjusted; for example, Figure 1 is too small and the writing is not visible. On the contrary, Figure 22 is presented too large.

**Comment by ghobona** [comment]
@TaehoonK I managed to fix the caption styles. The was that there were some tables and figure that still had the asciidoctor way of creating numbered captions. You can see the edits that were made at https://github.com/opengeospatial/ogcapi-movingfeatures/pull/49/commits/d53dc518f395d544992b0b928e122e058b1a542d

I also managed to make Figure 23 (formerly Figure 22) smaller. 

I specified a larger width of Figure 1 but the image size did not change on the HTML. We can look into this further after merging.

I'm proceeding with merging the PR.

**Pull request merged**
